name: Linux

on: [push, pull_request]

jobs:
  Linux:
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yq libgtest-dev libboost-program-options-dev rapidjson-dev ninja-build

    - name: Build GTest
      run: |
        cmake -E make_directory gtest
        cd gtest
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.config }} -G Ninja /usr/src/gtest
        cmake --build . -j -v
        sudo cmake --install .

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure CMake
      shell: pwsh
      working-directory: build/
      run: |
        $cmakeBuildType = '${{ matrix.config }}'

        cmake "-DCMAKE_BUILD_TYPE=$cmakeBuildType" -G Ninja ${{ github.workspace }}

    - name: Build
      working-directory: build/
      run: cmake --build . -j -v

    - name: Test
      working-directory: build/
      run: ctest --output-on-failure
