name: macOS

on: [push, pull_request]

jobs:
  xcode:
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Cache vcpkg
      uses: actions/cache@v3
      id: cache-vcpkg
      with:
        path: build/vcpkg_cache/
        key: vcpkg-binaries-x64-osx

    - name: Create Build Environment
      if: ${{ !steps.cache-vcpkg.outputs.cache-hit }}
      run: |
        cmake -E make_directory build
        cmake -E make_directory build/vcpkg_cache

    - name: Configure
      shell: pwsh
      working-directory: build/
      run: |
        $vcpkgToolchain = Join-Path $env:VCPKG_INSTALLATION_ROOT './scripts/buildsystems/vcpkg.cmake' -Resolve
        $cmakeBuildType = '${{ matrix.config }}'

        $cachedBinaries = Join-Path $(Get-Location) './vcpkg_cache/' -Resolve
        $cacheAccess = $(if ('${{ steps.cache-vcpkg.outputs.cache-hit }}' -eq 'true') { 'read' } else { 'write' })
        $env:VCPKG_BINARY_SOURCES = "clear;files,$cachedBinaries,$cacheAccess"

        cmake "-DCMAKE_TOOLCHAIN_FILE=$vcpkgToolchain" "-DCMAKE_BUILD_TYPE=$cmakeBuildType" ${{ github.workspace }}

    - name: Build
      working-directory: build/
      run: cmake --build . -j -v

    - name: Test
      working-directory: build/
      run: ctest --output-on-failure
